package util;

public class MineralNames {
    static final String[] names = { "Acerila", "Cornelian", "Kingman Turquoise",
            "Precious Cat's Eye", "Achroite", "Cornflower Sapphire",
            "Precious Fire Opal", "Acmite", "Coyamito Agate", "Kittlite",
            "Precious Opal", "Adamine", "Crazy Lace Agate", "Kunzite",
            "Pseudoleucite", "Adularia", "Crocidolite", "Kutnohorite",
            "Purple Copper Ore", "African Amethyst", "Cromfordite",
            "Laguna Agate", "Pycnite", "African Jade", "Cromite",
            "Lake Superior Agate", "Pyralspite", "Agalmatolite",
            "Cronstedtite", "Landscape Agate", "Pyrite Cube", "Agaric Mineral",
            "Crystal Opal", "Lapis", "Aluminum",
            "Amphibole",
            "Andesite",
            "Antimony",
            "Aragonite",
            "Arsenic",
            "Asbestos",
            "Augite",
            "Aurichalcite",
            "Autunite",
            "Barium",
            "Basalt",
            "Beryllium",
            "Biotite",
            "Bismuth",
            "Boron",
            "Brentamite",
            "Bromine",
            "Cadmium",
            "Calcite",
            "Cement",
            "Cesium",
            "Chert",
            "Chertjas",
            "Chlorite",
            "Chromium",
            "Clays",
            "Coal",
            "Cobalt",
            "Colemanite",
            "Columbite",
            "Conglomerate",
            "Copper",
            "Corundum",
            "Creeoite",
            "Diamond",
            "Diatomite",
            "Dimension Stone",
            "Diorite",
            "Dolomite",
            "Feldspar",
            "Fluorite",
            "Gabbro",
            "Galena",
            "Gallium",
            "Germanium",
            "Gold",
            "Granite",
            "Graphite",
            "Gypsum",
            "Hafnium",
            "Helium",
            "Indium",
            "Iodine",
            "Iron",
            "Kaolin",
            "Kyanite",
            "Lead",
            "Limestone",
            "Lithium",
            "Manganese",
            "Mercury",
            "Mica",
            "Molybdenum",
            "Nickel",
            "Nitrogen",
            "Obsidian",
            "Peat",
            "Perlite",
            "Plagioclase",
            "Platinum",
            "Potash",
            "Pumice",
            "Pyrite",
            "Quartz",
            "Quartzite",
            "Rhenium",
            "Rubidium",
            "Rutile",
            "Salt",
            "Sandstone",
            "Scandium",
            "Selenium",
            "Shale",
            "Silica",
            "Silver",
            "Slate",
            "Strontium",
            "Sulfur",
            "Talc",
            "Tantalum",
            "Tellurium",
            "Thallium",
            "Thorium",
            "Tin",
            "Titanium",
            "Traprock",
            "Tungsten",
            "Vanadium",
            "Vermiculite",
            "Zeolites",
            "Zinc",
            "Zirconium" };
    
    public static String getName() {
        return names[(int)(Math.random() * (names.length - 1))];
    }
}
